export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PENDING_L1 = 'PENDING_L1',
  PENDING_L2 = 'PENDING_L2',
  PENDING_L3 = 'PENDING_L3',
  PENDING_L4 = 'PENDING_L4',
  PENDING_L5 = 'PENDING_L5',
  PENDING_L6 = 'PENDING_L6',
  PENDING_L7 = 'PENDING_L7',
  RETURNED = 'RETURNED',
  RESUBMITTED = 'RESUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  AUTO_REJECTED = 'AUTO_REJECTED',
}

export enum ApprovalAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  RETURN = 'RETURN',
  ESCALATE = 'ESCALATE',
  AUTO_APPROVE = 'AUTO_APPROVE',
  AUTO_REJECT = 'AUTO_REJECT',
}

export enum ApprovalLevel {
  L1 = 1,
  L2 = 2,
  L3 = 3,
  L4 = 4,
  L5 = 5,
  L6 = 6,
  L7 = 7,
}

export enum UserRole {
  SALE = 'SALE',
  CREDIT_OFFICER = 'CREDIT_OFFICER',
  SENIOR_CREDIT_OFFICER = 'SENIOR_CREDIT_OFFICER',
  CREDIT_SUPERVISOR = 'CREDIT_SUPERVISOR',
  CREDIT_MANAGER = 'CREDIT_MANAGER',
  CREDIT_DIRECTOR = 'CREDIT_DIRECTOR',
  VP_CREDIT = 'VP_CREDIT',
  CREDIT_COMMITTEE = 'CREDIT_COMMITTEE',
  ADMIN = 'ADMIN',
  AUDIT = 'AUDIT',
}

export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  FILE_UPLOAD = 'FILE_UPLOAD',
}

export enum ScoringModelType {
  SIMPLE_SUM = 'SIMPLE_SUM',
  WEIGHTED_AVERAGE = 'WEIGHTED_AVERAGE',
  RULE_BASED = 'RULE_BASED',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  IN_APP = 'IN_APP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  APPLICATION_SUBMIT = 'APPLICATION_SUBMIT',
  APPLICATION_APPROVE = 'APPLICATION_APPROVE',
  APPLICATION_REJECT = 'APPLICATION_REJECT',
  APPLICATION_RETURN = 'APPLICATION_RETURN',
  ANSWER_SAVE = 'ANSWER_SAVE',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  APPROVAL_MATRIX_CHANGE = 'APPROVAL_MATRIX_CHANGE',
  SENSITIVE_DATA_ACCESS = 'SENSITIVE_DATA_ACCESS',
  CONFIG_CHANGE = 'CONFIG_CHANGE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  DELEGATION_CREATE = 'DELEGATION_CREATE',
}

export enum BlacklistType {
  NATIONAL_ID = 'NATIONAL_ID',
  PHONE = 'PHONE',
  NAME = 'NAME',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
